name: .NET Build & Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.cs"
      - "**.xaml"
      - "**.csproj"

env:
  DotnetVersion: "6.0.x"

jobs:
  build-and-test:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set the value in pwsh
        run: |
          "OutputDirectory=HashTool-$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV
          "UserProfile=$env:USERPROFILE" >> $env:GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DotnetVersion }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.UserProfile }}/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: |
          dotnet build HashTool `
            --configuration ${{ matrix.configuration }} `
            --output ./HashTool/bin/${{ matrix.configuration }}/${{ env.OutputDirectory }} `
            --no-restore
          dotnet build HashToolTest `
            --configuration ${{ matrix.configuration }} `
            --output ./HashToolTest/bin/${{ matrix.configuration }}/${{ env.OutputDirectory }} `
            --no-restore
      - name: Test
        run: |
          dotnet test `
            --configuration ${{ matrix.configuration }} `
            --output ./HashToolTest/bin/${{ matrix.configuration }}/${{ env.OutputDirectory }} `
            --no-build `
            --verbosity normal
      - name: Upload bin directory
        uses: actions/upload-artifact@v3
        if: success() && ${{ matrix.configuration }} == 'Release'
        with:
          name: ${{ env.OutputDirectory }}
          path: ./HashTool/bin/Release/${{ env.OutputDirectory }}
