name: .NET Build & Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    paths:
      - "**.cs"
      - "**.xaml"
      - "**.csproj"

env:
  DotnetVersion: "6.0.x"

jobs:
  build-and-test:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set the OutputDirectory in pwsh
        run: |
          "OutputDirectory=HashTool-$(git rev-parse --short HEAD)" >> $env:GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DotnetVersion }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: |
          dotnet build `
            --configuration ${{ matrix.configuration }} `
            --output ./bin/${{ matrix.configuration }}/${{ env.OutputDirectory }} `
            --no-restore
      - name: Test
        run: |
          dotnet test `
            --configuration ${{ matrix.configuration }} `
            --output ./bin/${{ matrix.configuration }}/${{ env.OutputDirectory }} `
            --no-build `
            --verbosity normal
      - name: Upload bin directory
        uses: actions/upload-artifact@v3
        if: ${{ success() }}
        with:
          name: ${{ env.OutputDirectory }}
          path: ./bin/Release/${{ env.OutputDirectory }}
